### ISSUE TITLE
feature request:  Generate HTML report

### ISSUE THREAD

**Issue by pawamoy** [brandtbucher/specialist#1]
## Pretty!

I'd love to be able to integrate the output of specialist into my docs, just like I already integrate [coverage reports](https://mkdocstrings.github.io/griffe/coverage/). I'm probably a bit early :smile:

![specialist](https://user-images.githubusercontent.com/3999221/172365934-86726837-9644-4bd3-8d92-c7ac01748610.png)

**Comment by brandtbucher** [comment]
Hi @pawamoy! The first issue is always fun to see, since it means people are actually *using* the thing. :wink:

Just to clarify what you're asking for here: are you looking for a way to get the generated HTML directly, rather than viewing it through a web browser? If so, would an option like `-o <path>`/`--output <path>` (where `<path>` is a directory to write HTML files out to) fit your needs?

**Comment by pawamoy** [comment]
Yes! That would be perfect :slightly_smiling_face: 
I would then be able to include the pages in iframes.

**Comment by brandtbucher** [comment]
I've added this feature on `main`. When you get a chance, play with it and let me know how it works for you. If it looks good, I can probably cut a new release tomorrow.

**Comment by realsaeedhassani** [comment]
> Hi @pawamoy! The first issue is always fun to see, since it means people are actually _using_ the thing. wink
> 
> Just to clarify what you're asking for here: are you looking for a way to get the generated HTML directly, rather than viewing it through a web browser? If so, would an option like `-o <path>`/`--output <path>` (where `<path>` is a directory to write HTML files out to) fit your needs?

That's great @brandtbucher
